### ISSUE TITLE
Magnet Icon Doesn't Appear

### ISSUE THREAD

**Issue by andrewjmetzger** [mems/torrentz-magnet#4]
On Torrentz2, the magnet icon does not appear next to the inserted link (see below). Otherwise, the script works as intended, thank you for providing it. In truth, the missing icon is a minor issue at most, but you should still be made aware.

![image](https://cloud.githubusercontent.com/assets/590246/22140536/109ee890-debb-11e6-8bb8-9b486412ced5.png)

I would think this has something to do with reworked HTML element selectors; however, I'm not good with selections from the DOM, and this is just a guess. 

Chrome's script console also provides a possibly-relevant error when the page loads. It occurs at position 63:7 in the script.
> Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-jcfIVO/5j1k051VfHT7NAirBLgKDkU/zYdbqyhuCecE='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

I am not sure what to make of that, but I hope it helps!

**Comment by andrewjmetzger** [comment]
Quick update for a few things based on more investigation:

* The image does not load. a `0 x 0 px` sized span is created instead, and it is never resized for the `16 x 16 px` image.
* Base64 images generally terminate with 3 equals-signs. I adjusted these in the script (only 1 was present before), to no effect. To quickly generate Base64 image codes, try [this page](http://www.motobit.com/util/base64/css-images-to-base64.asp?url=http%3A%2F%2Ftamilrockers.ac%2Fpublic%2Fstyle_extra%2Fbbcode_icons%2Fmagnet.png) (The pre-set URL is an alternative magnet icon used to test the issue).
* Moving the image from the `span` background to a dedicated child image did resize the span from `0 x 0 px` to fit the image, but it doesn't load. Chrome still complains: 
> Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFW...3U3yL/hwJSNL8IfPSFkolm1Yv+CxHODE58X6fHc/8KMADEDy35bASZVQAAAABJRU5ErkJggg===' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

As far as I'm aware, the quickest workaround for CSP should be using [`@grant unsafeWindow`](https://wiki.greasespot.net/UnsafeWindow) in Greasemonkey (Tampermonkey docs [here](http://tampermonkey.net/documentation.php?ext=dhdg&show=dhdg#unsafeWindow)). This is incredibly volatile, though, and I could not get it to work in Chrome.

Thoughts welcome.

**Comment by mems** [comment]
Magnet icon is now provided by Torrentz2 with the CSS class `s197`. That fix the CSP problem with data URIs

Note: base64 data don't always end by equal sign (could be 0, 1 or 2 pad char). See the [RFC-4648 section 4 - Base 64 Encoding](https://tools.ietf.org/html/rfc4648#section-4). It's depends on the number of bytes to encode .

Fixed in 9689df5
