### ISSUE TITLE
Some trackers to add/delete

### ISSUE THREAD

**Issue by Matthi3u** [mems/torrentz-magnet#5]
Hi I can't create a pull request...
See here this site for update zer0day tracker http://zer0day.to/ and http://tracker.coppersurfer.tk/

More here : 
https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt
Its update frequently.

**Comment by mems** [comment]
I can't automatically update the default tracker list yet (see #6). I just update the current list + add reference to some available lists
